 /*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.entrc_gui;

import com.jakubwawak.database.Database_Connector;
import com.jakubwawak.database.Database_Worker;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *Object for adding worker
 * @author jakubwawak
 */
public final class addworker_window extends javax.swing.JDialog {

    /**
     * Creates new form addworker_window
     */
    Database_Connector database;
    Database_Worker dw;
    int mode;
    
    public addworker_window(javax.swing.JDialog parent, boolean modal,Database_Connector database,int mode) throws SQLException {
        super(parent, modal);
        this.database = database;
        this.mode = mode;
        dw = new Database_Worker(this.database);
        initComponents();
        load_window();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        field_name = new javax.swing.JTextField();
        field_surname = new javax.swing.JTextField();
        field_position = new javax.swing.JTextField();
        button_add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        button_editpin = new javax.swing.JButton();
        field_pin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj pracownika");
        setIconImage(null);

        jLabel1.setText("imię");

        jLabel2.setText("nazwisko:");

        jLabel3.setText("stanowisko:");

        button_add.setText("Dodaj");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        jLabel4.setText("PIN:");

        button_editpin.setText("Edytuj PIN");
        button_editpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editpinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(field_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_editpin, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addComponent(field_name)
                            .addComponent(field_surname)
                            .addComponent(field_position))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_position, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_editpin)
                    .addComponent(field_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_add)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_editpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editpinActionPerformed
        if (mode == 0){    
            switch (button_editpin.getText()) {
                case "Edytuj PIN":
                    field_pin.setEnabled(true);
                    button_editpin.setText("Sprawdź");
                    break;
                case "Sprawdź":
                    try {
                        if ( dw.get_worker_id_bypin(field_pin.getText()) == 0){
                            field_pin.setEnabled(false);
                            button_editpin.setText("Zapisano");
                        }
                        else{
                            button_editpin.setText("Błąd");
                        }
                    } catch (SQLException ex) {
                        new message_window_jdialog(this,true,"Błąd: "+ex.toString());
                        Logger.getLogger(addworker_window.class.getName()).log(Level.SEVERE, null, ex);
                    }   break;
                case "Błąd":
                    field_pin.setEnabled(false);
                    try {
                        field_pin.setText(dw.enroll_pin());
                    } catch (SQLException ex) {
                        new message_window_jdialog(this,true,"Błąd: "+ex.toString());
                        Logger.getLogger(addworker_window.class.getName()).log(Level.SEVERE, null, ex);
                    }   button_editpin.setText("Edytuj PIN");
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_button_editpinActionPerformed

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        if( button_add.getText().equals("Dodaj") ){
            try {
                String pin = dw.add_worker(field_name.getText(), field_surname.getText(), field_pin.getText(), field_position.getText());
                if ( pin != null ){
                    button_add.setText("Dodano. PIN:"+pin);
                    field_name.setEnabled(false);
                    field_surname.setEnabled(false);
                    field_position.setEnabled(false);
                    button_add.setEnabled(false);
                    this.setTitle("Możesz zamknąć okno");
                }
            } catch (SQLException ex) {
                new message_window_jdialog(this,true,"Błąd: "+ex.toString());
                Logger.getLogger(addworker_window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {
                if ( dw.update_worker(mode, field_name.getText(), field_surname.getText(), field_position.getText())){
                    button_add.setText("Zaktualizowano dane");
                    field_name.setEnabled(false);
                    field_surname.setEnabled(false);
                    field_position.setEnabled(false);
                    button_add.setEnabled(false);
                    this.setTitle("Możesz zamknąć okno");
                }
            } catch (SQLException ex) {
                new message_window_jdialog(this,true,"Błąd: "+ex.toString());
                Logger.getLogger(addworker_window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_button_addActionPerformed
    void load_window() throws SQLException{
        if (mode != 0){
            ArrayList<String> data = dw.get_worker_byid(mode);
            
            if ( data != null ){
                this.setTitle("Aktualizuj dane pracownika");
                field_name.setText(data.get(0));
                field_surname.setText(data.get(1));
                field_position.setText(data.get(2));
                field_pin.setText(data.get(3));
                button_editpin.setEnabled(false);
                button_add.setText("Aktualizuj");
                field_pin.setEnabled(false);
            }
        }
        else{
            field_pin.setText(dw.enroll_pin());
            field_pin.setEnabled(false);
        }
    }
    /**
     * Function for validating fields
     * @return boolean
     * @throws SQLException 
     */
    boolean validate_fields() throws SQLException{
        return !field_name.getText().isBlank() && !field_surname.getText().isBlank() 
                && !field_position.getText().isBlank() && !field_pin.getText().isBlank();
            
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_editpin;
    private javax.swing.JTextField field_name;
    private javax.swing.JTextField field_pin;
    private javax.swing.JTextField field_position;
    private javax.swing.JTextField field_surname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
