/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.entrc_gui;

import com.jakubwawak.database.Database_Announcement;
import com.jakubwawak.database.Database_Connector;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *Window for implementing annoucment data
 * @author jakubwawak
 */
public class announcement_window extends javax.swing.JDialog {

    /**
     * Creates new form announcement_window
     */
    Database_Connector database;
    
    public announcement_window(java.awt.Frame parent, boolean modal,Database_Connector database) {
        super(parent, modal);
        this.database = database;
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setBackground(Color.black);
        load_view();
        setVisible(true);
    }
    
    /**
     * Function for loading window
     */
    void load_view(){
        Database_Announcement da = new Database_Announcement(database);
        try {
            field_data.setText(da.load_newestannouncement());
        } catch (SQLException ex) {
            new message_window_jdialog(this,true,"Błąd:\n"+ex.toString());
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_close = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_data = new javax.swing.JTextArea();
        label_updatetime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        button_close.setBackground(new java.awt.Color(0, 0, 0));
        button_close.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        button_close.setForeground(new java.awt.Color(255, 255, 255));
        button_close.setText("ZAMKNIJ");
        button_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_closeActionPerformed(evt);
            }
        });

        field_data.setBackground(new java.awt.Color(0, 0, 0));
        field_data.setColumns(20);
        field_data.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        field_data.setForeground(new java.awt.Color(255, 255, 51));
        field_data.setRows(5);
        field_data.setText("test usługi");
        jScrollPane1.setViewportView(field_data);

        label_updatetime.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label_updatetime.setForeground(new java.awt.Color(255, 255, 255));
        label_updatetime.setText("OSTATNIA AKTUALIZACJA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(button_close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_updatetime)
                        .addGap(0, 807, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_updatetime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_closeActionPerformed
        dispose();
    }//GEN-LAST:event_button_closeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_close;
    private javax.swing.JTextArea field_data;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_updatetime;
    // End of variables declaration//GEN-END:variables
}
