/*
by Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package com.jakubwawak.entrc_gui;

import com.jakubwawak.entrc.Data_Worker_Connector;
import com.jakubwawak.database.Database_Connector;
import com.jakubwawak.database.Database_Data_Dump;
import com.jakubwawak.database.Database_Data_Import;
import com.jakubwawak.database.Database_Worker;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;

/**
 *Object for creating managment window
 * @author kubaw
 */
public class manage_workers_window extends javax.swing.JDialog {

    /**
     * Creates new form manage_workers_window
     */
    Database_Connector database;
    String list_selected;
    public manage_workers_window(java.awt.Frame parent, boolean modal,Database_Connector database) throws SQLException {
        super(parent, modal);
        this.database = database;
        list_selected = "";
        initComponents();
        this.setLocationRelativeTo(null);
        load_window();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_workers = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        button_addworker = new javax.swing.JButton();
        button_editworker = new javax.swing.JButton();
        button_export = new javax.swing.JButton();
        button_import = new javax.swing.JButton();
        button_exportPIN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zarządzanie Pracownikami");

        list_workers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_workers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_workersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_workers);

        jLabel1.setText("Lista pracowników");

        button_addworker.setText("Dodaj pracownika");
        button_addworker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addworkerActionPerformed(evt);
            }
        });

        button_editworker.setText("Edytuj pracownika");
        button_editworker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editworkerActionPerformed(evt);
            }
        });

        button_export.setText("Eksportuj do pliku");
        button_export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exportActionPerformed(evt);
            }
        });

        button_import.setText("Importuj z pliku");
        button_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_importActionPerformed(evt);
            }
        });

        button_exportPIN.setText("Eksportuj dane PIN");
        button_exportPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_exportPINActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_addworker, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_editworker, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_import, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_exportPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_addworker, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_editworker, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(button_import, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(button_exportPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_addworkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addworkerActionPerformed
        try {
            new addworker_window(this,true,database,0);
            reload_list();
        } catch (SQLException ex) {
            new message_window_jdialog(this,true,"Błąd: "+ex.toString());
            Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_button_addworkerActionPerformed

    private void list_workersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_workersMouseClicked
        list_selected = list_workers.getSelectedValue().split(":")[0];
    }//GEN-LAST:event_list_workersMouseClicked

    private void button_editworkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editworkerActionPerformed
        if (!list_selected.equals("")){
            try{
                int worker_id = Integer.parseInt(list_selected);
                
                new addworker_window(this,true,database,worker_id);
                reload_list();
            
            }catch(NumberFormatException e){
                new message_window_jdialog(this,true,"Błąd NumberFormatException");
                try {
                    reload_list();
                } catch (SQLException ex) {
                    new message_window_jdialog(this,true,"Błąd: "+ex.toString());
                    Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                new message_window_jdialog(this,true,"Błąd: "+ex.toString());
                Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_button_editworkerActionPerformed

    private void button_exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exportActionPerformed
        String path = "worker_list"+get_hours()+".txt";
        Database_Data_Dump ddd = new Database_Data_Dump(database);
        try {
            Data_Worker_Connector dc = new Data_Worker_Connector(path,0);
            dc.write_file(ddd.dump_worker_data());
            new message_window_jdialog(this,true,"Zapisano do pliku");
        } catch (IOException ex) {
            Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
            new message_window_jdialog(this,true,"Błąd: "+ex.toString());
        } catch (SQLException ex) {
            Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
            new message_window_jdialog(this,true,"Błąd: "+ex.toString());
        }

    }//GEN-LAST:event_button_exportActionPerformed

    private void button_exportPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_exportPINActionPerformed
        Database_Data_Dump ddd = new Database_Data_Dump(database);
        try {
            Data_Worker_Connector dwc = new Data_Worker_Connector("worker_pin_dump.txt",0);
            dwc.write_file(ddd.dump_worker_data());
            new message_window_jdialog(this,true,"Dane zaimportowno");
        } catch (IOException ex) {
            Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
            new message_window_jdialog(this,true,"Błąd: "+ex.toString());
        } catch (SQLException ex) {
            Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
            new message_window_jdialog(this,true,"Błąd: "+ex.toString());
        }
        
    }//GEN-LAST:event_button_exportPINActionPerformed

    private void button_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_importActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        if ( jfc.showOpenDialog(null) != JFileChooser.APPROVE_OPTION){
            new message_window_jdialog(this,true,"Nie dokonano wyboru");
        }
        else{
            // opened file
            String path_file = jfc.getSelectedFile().getAbsolutePath();
            try {
                Data_Worker_Connector dwc = new Data_Worker_Connector(path_file,1);
                if ( dwc.exists ){
                    Database_Data_Import ddi = new Database_Data_Import(database);
                    ddi.import_workers(dwc);
                }
            } catch (IOException ex) {
                Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
                new message_window_jdialog(this,true,"Błąd: "+ex.toString());
            } catch (SQLException ex) {
                Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
                new message_window_jdialog(this,true,"Błąd: "+ex.toString());
            }
        }
    }//GEN-LAST:event_button_importActionPerformed
    /**
     * Function for reloading list of users
     * @throws SQLException 
     */
    void reload_list() throws SQLException{
        Database_Worker dw = new Database_Worker(database);
        ArrayList<String> list = dw.get_all_workers();
        DefaultListModel dlm = new DefaultListModel();
        dlm.addAll(list);
        
        list_workers.setModel(dlm);
    }
    /**
     * Function for loading all components
     */
    void load_window() throws SQLException{
        reload_list();
    }     
    /**
     * Function for getting hours
     * @return String
     */
    String get_hours(){
        Date actual_date = new Date();
        String[] elements = actual_date.toString().split(" ");
        String data_toRet = "";
        for (int i = 0; i < elements[3].length(); i++) {
            if( elements[3].charAt(i) == ':' ){
                data_toRet = data_toRet + String.valueOf("");
            }
            else{
                data_toRet = data_toRet + String.valueOf(elements[3].charAt(i));
            }
        }
        return data_toRet;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_addworker;
    private javax.swing.JButton button_editworker;
    private javax.swing.JButton button_export;
    private javax.swing.JButton button_exportPIN;
    private javax.swing.JButton button_import;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_workers;
    // End of variables declaration//GEN-END:variables
}
