/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jakubwawak.entrc;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author kubaw
 */
public class manage_workers_window extends javax.swing.JDialog {

    /**
     * Creates new form manage_workers_window
     */
    Database_Connector database;
    String list_selected;
    public manage_workers_window(java.awt.Frame parent, boolean modal,Database_Connector database) throws SQLException {
        super(parent, modal);
        this.database = database;
        list_selected = "";
        initComponents();
        load_window();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_workers = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        button_addworker = new javax.swing.JButton();
        button_deleteworker = new javax.swing.JButton();
        button_editworker = new javax.swing.JButton();
        button_export = new javax.swing.JButton();
        button_import = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        list_workers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_workers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_workersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_workers);

        jLabel1.setText("Lista pracowników");

        button_addworker.setText("Dodaj pracownika");
        button_addworker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addworkerActionPerformed(evt);
            }
        });

        button_deleteworker.setText("Usuń pracownika");
        button_deleteworker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteworkerActionPerformed(evt);
            }
        });

        button_editworker.setText("Edytuj pracownika");
        button_editworker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editworkerActionPerformed(evt);
            }
        });

        button_export.setText("Eksportuj do pliku");

        button_import.setText("Importuj z pliku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_editworker, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_addworker, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_deleteworker, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_import, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(button_addworker, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_editworker, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_deleteworker, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_import, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_addworkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addworkerActionPerformed
        try {
            new addworker_window(this,true,database,0);
            reload_list();
        } catch (SQLException ex) {
            Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_button_addworkerActionPerformed

    private void list_workersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_workersMouseClicked
        list_selected = list_workers.getSelectedValue().split(":")[0];
    }//GEN-LAST:event_list_workersMouseClicked

    private void button_editworkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editworkerActionPerformed
        if (!list_selected.equals("")){
            try{
                int worker_id = Integer.parseInt(list_selected);
                
                new addworker_window(this,true,database,worker_id);
                reload_list();
            
            }catch(NumberFormatException e){
                new message_window_jdialog(this,true,"Błąd NumberFormatException");
                try {
                    reload_list();
                } catch (SQLException ex) {
                    Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(manage_workers_window.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_button_editworkerActionPerformed

    private void button_deleteworkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteworkerActionPerformed
        new message_window_jdialog(this,true,"Funkcja nieobsługiwana");
    }//GEN-LAST:event_button_deleteworkerActionPerformed
    /**
     * Function for reloading list of users
     * @throws SQLException 
     */
    void reload_list() throws SQLException{
        Database_Worker dw = new Database_Worker(database);
        ArrayList<String> list = dw.get_all_workers();
        DefaultListModel dlm = new DefaultListModel();
        dlm.addAll(list);
        
        list_workers.setModel(dlm);
    }
    /**
     * Function for loading all components
     */
    void load_window() throws SQLException{
        reload_list();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_addworker;
    private javax.swing.JButton button_deleteworker;
    private javax.swing.JButton button_editworker;
    private javax.swing.JButton button_export;
    private javax.swing.JButton button_import;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_workers;
    // End of variables declaration//GEN-END:variables
}
